### ISSUE TITLE
Is close method required

### ISSUE THREAD

**Issue by spacedmonkey** [johnjamesjacoby/ludicrousdb#5]
The close method was added [here](https://github.com/johnjamesjacoby/ludicrousdb/commit/edbbb0adb48d58efdde63ec5f20988ef40c77299) . This brings ludicrousdb into line with [changes in core](https://core.trac.wordpress.org/ticket/34903). However, the close method is a copy and paste from what is in core in 4.5. Meaning it is overriding the close method with the same code. This is fine, but if the logic is exactly the same as core, it should be removed, as if you remove it, then it will just use the core method. This means if any changed happen in core, they will be reflected.

**Comment by johnjamesjacoby** [comment]
The `close()` method in LudicrousDB is now a bit different than what comes with WPDB, so I think it's okay to close this.

As with all of the overlapping methods, it's good to keep an eye on core to merge anything back in that needs it.
